# Generated by Django 3.2.8 on 2021-10-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemdutystructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdutystructure',
            name='acd',
        ),
        migrations.RemoveField(
            model_name='itemdutystructure',
            name='customDuty',
        ),
        migrations.RemoveField(
            model_name='itemdutystructure',
            name='incomeTax',
        ),
        migrations.RemoveField(
            model_name='itemdutystructure',
            name='rd',
        ),
        migrations.RemoveField(
            model_name='itemdutystructure',
            name='salesTax',
        ),
    ]
