# Generated by Django 3.2.8 on 2021-10-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20211018_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdutystructure',
            old_name='customeDutyRate',
            new_name='cdRate',
        ),
    ]
