# Generated by Django 3.2.8 on 2021-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_customedutyrate_itemdutystructure_cdrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdutystructure',
            name='cdType',
            field=models.CharField(choices=[('%', '%'), ('F', 'F')], default='%', max_length=5),
        ),
        migrations.AddField(
            model_name='itemdutystructure',
            name='fedType',
            field=models.CharField(choices=[('%', '%'), ('F', 'F')], default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='itemdutystructure',
            name='rdType',
            field=models.CharField(choices=[('%', '%'), ('F', 'F')], default='F', max_length=5),
        ),
    ]
