# Generated by Django 3.2.8 on 2021-10-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('bl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl',
            name='isTerminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bl',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.terminal'),
        ),
    ]
