# Generated by Django 3.2.9 on 2021-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211111_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
