# Generated by Django 3.2.9 on 2021-11-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='eto',
            field=models.BooleanField(default=True),
        ),
    ]
