# Generated by Django 3.2.8 on 2021-10-15 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('item', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdType', models.CharField(choices=[('IB', 'INTO BOND'), ('EB', 'EX BOND'), ('ST', 'SAFE TRANSPORTAION'), ('HC', 'HOME CONSUMPTION')], default='IB', max_length=20)),
                ('lcNo', models.CharField(max_length=100)),
                ('lcDate', models.DateField()),
                ('totalQuantity', models.FloatField()),
                ('vessel', models.CharField(max_length=100)),
                ('igm', models.IntegerField()),
                ('igmDate', models.DateField()),
                ('totalBL', models.IntegerField()),
                ('dv', models.FloatField()),
                ('av', models.FloatField()),
                ('exRate', models.FloatField()),
                ('insurance', models.FloatField()),
                ('pqaRate', models.FloatField()),
                ('pqaCharges', models.FloatField()),
                ('billed', models.BooleanField(default=False)),
                ('psqc', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.port')),
            ],
        ),
    ]
