# Generated by Django 3.2.8 on 2021-10-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='pqaCharges',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
