# Generated by Django 3.2.7 on 2021-10-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0002_alter_lc_pqacharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='fed',
            field=models.FloatField(default=13),
        ),
        migrations.AlterField(
            model_name='lc',
            name='pqaRate',
            field=models.FloatField(default=31),
        ),
    ]
