# Generated by Django 3.2.9 on 2021-11-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0004_auto_20211028_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lc',
            options={'ordering': ['-igm']},
        ),
        migrations.AddField(
            model_name='lc',
            name='igmNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
