# Generated by Django 3.2.9 on 2021-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc', '0005_auto_20211111_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='lcDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
